### ISSUE TITLE
Fuel gauge not precise

### ISSUE THREAD

**Issue by radiodrag** [Bluethefurry/SexySpeedometer-FiveM#1]
the regular equation (80.0+FuelLevel/MaxFuelLevel*110) set the fuel gauge too high when fuel is full, I tried to mess a bit with it but i can't find the sweet spot, sometime at 50% fuel, the gauge is at 50% too, but go too high when full or too low when empty

**Comment by Blumlaut** [comment]
that is considered normal behaviour, the fuel gauge was copied from my car, there it behaves nearly identical ( e.g. "full" means the needle is NEXT to the F, not ontop of it, same if its running on fumes ), to make it more precise you may have to add more code.
