### ISSUE TITLE
over fueled?

### ISSUE THREAD

**Issue by rahafuf** [Bluethefurry/SexySpeedometer-FiveM#3]
for some reason my fuel is way over the full mark. How would I go about fixing this?? at 65% it is on fuel.

**Comment by Blumlaut** [comment]
what fuel system are you using? most likely the system doesnt respect your vehicles maximum fuel amount.

**Comment by rahafuf** [comment]
LegacyFuel

**Comment by rahafuf** [comment]
still having this issue and some cars the speedo just spins making it look like your doing 220+ when your doing 100

**Comment by Blumlaut** [comment]
"in some cars", gonna need something to reproduce the issue with.

**Comment by rahafuf** [comment]
well its a constant with those vehicles is doing it on so not really sure how to reproduce it

**Comment by thecrankytech** [comment]
> well its a constant with those vehicles is doing it on so not really sure how to reproduce it

I literally made an account to comment on this lmao.

Maybe provide a link to the cars that happen to be doing it could possibly help? saying "those vehicles" still doesn't help

**Comment by rahafuf** [comment]
They are custom vehicles that I have created so id rather not

**Comment by Blumlaut** [comment]
if you cannot provide something i can reproduce it then its a "wont fix", it works fine for everyone i've seen use it, reopen this issue if you can provide ZIP of resources/cars this issue occurs with.

**Comment by rahafuf** [comment]
well im not going to give you a model that i made... plus from what it seems on your closed tickets there is an issue with the fuel gauge

**Comment by rahafuf** [comment]
i can send you a video of it but i cannot send you the vehicle itself

**Comment by Blumlaut** [comment]
if there is an issue with the fuel gauge, send a zip of an environment i can reproduce it with, a video is useless in such a case, if you cant provide something i can actually test it with, you might aswell not send anything.
edit: if the gauge didnt work, many more people would report it, dont you think?

**Comment by rahafuf** [comment]
Let see if any cars of gta5-mods does it
